### ISSUE TITLE
Notebooks not showing

### ISSUE THREAD

**Issue by schmoelder** [spyder-ide/spyder-notebook#386]
## Description of your problem

I was very happy to read that a new version of spyder-notebooks was released and I immediately wanted to try it out. However, I could not get it to run. 

**What steps will reproduce the problem?**

1. Install Spyder with `conda install spyder -c conda-forge`
2. Install spyder-notebook with `conda install spyder-notebook -c conda-forge`
3. Open Spyder, Go to Notebooks Tab.
4. Nothing happens.

**What is the expected output? What do you see instead?**

I would expect the notebooks to show. However, I get a "blank" page (see screenshot below).

**Please provide any additional information below (stack trace, screenshots, a gif, etc)**

![image](https://user-images.githubusercontent.com/20299934/195356139-8d11dcbb-1ccb-4e7e-b935-381dabd84177.png)

When I click on `Open a new Notebook`, a new tab appears which is also empty.
If I try to open an existing notebook, nothing happens.

I don't know if it helps but if I run `import spyder_notebook`, I get the following error:

```
Qt WebEngine seems to be initialized from a plugin. Please set Qt::AA_ShareOpenGLContexts using QCoreApplication::setAttribute before constructing QGuiApplication.
Traceback (most recent call last):

  File "/tmp/ipykernel_414369/1627363730.py", line 1, in <cell line: 1>
    import spyder_notebook

  File "/home/jo/software/miniconda3/envs/chromapy/lib/python3.9/site-packages/spyder_notebook/__init__.py", line 11, in <module>
    from spyder_notebook.notebookplugin import NotebookPlugin as PLUGIN_CLASS

  File "/home/jo/software/miniconda3/envs/chromapy/lib/python3.9/site-packages/spyder_notebook/notebookplugin.py", line 19, in <module>
    from spyder_notebook.widgets.main_widget import NotebookMainWidget

  File "/home/jo/software/miniconda3/envs/chromapy/lib/python3.9/site-packages/spyder_notebook/widgets/main_widget.py", line 22, in <module>
    from spyder_notebook.widgets.notebooktabwidget import NotebookTabWidget

  File "/home/jo/software/miniconda3/envs/chromapy/lib/python3.9/site-packages/spyder_notebook/widgets/notebooktabwidget.py", line 30, in <module>
    from spyder_notebook.widgets.client import NotebookClient

  File "/home/jo/software/miniconda3/envs/chromapy/lib/python3.9/site-packages/spyder_notebook/widgets/client.py", line 20, in <module>
    from qtpy.QtWebEngineWidgets import (QWebEnginePage, QWebEngineSettings,

  File "/home/jo/software/miniconda3/envs/chromapy/lib/python3.9/site-packages/qtpy/QtWebEngineWidgets.py", line 29, in <module>
    from PyQt5.QtWebEngineWidgets import QWebEnginePage

ImportError: QtWebEngineWidgets must be imported before a QCoreApplication instance is created
```

## Versions and main components

* Spyder version: 5.3.3  (conda)
* Python version: 3.9.13 64-bit
* Qt version: 5.12.9
* PyQt5 version: 5.12.3
* Jupyter Notebook Version: 6.4.12
* Operating System: Linux 5.15.0-50-lowlatency

## Dependencies

\# Mandatory:
atomicwrites >=1.2.0                  :  1.4.1 (OK)
chardet >=2.0.0                       :  5.0.0 (OK)
cloudpickle >=0.5.0                   :  2.2.0 (OK)
cookiecutter >=1.6.0                  :  2.1.1 (OK)
diff_match_patch >=20181111           :  20200713 (OK)
intervaltree >=3.0.2                  :  3.0.2 (OK)
IPython >=7.31.1;<8.0.0               :  7.33.0 (OK)
jedi >=0.17.2;<0.19.0                 :  0.18.1 (OK)
jellyfish >=0.7                       :  0.9.0 (OK)
jsonschema >=3.2.0                    :  3.2.0 (OK)
keyring >=17.0.0                      :  23.9.3 (OK)
nbconvert >=4.0                       :  6.5.3 (OK)
numpydoc >=0.6.0                      :  1.5.0 (OK)
parso >=0.7.0;<0.9.0                  :  0.8.3 (OK)
pexpect >=4.4.0                       :  4.8.0 (OK)
pickleshare >=0.4                     :  0.7.5 (OK)
psutil >=5.3                          :  5.9.2 (OK)
pygments >=2.0                        :  2.13.0 (OK)
pylint >=2.5.0;<3.0                   :  2.15.3 (OK)
pyls_spyder >=0.4.0                   :  0.4.0 (OK)
pylsp >=1.5.0;<1.6.0                  :  1.5.0 (OK)
pylsp_black >=1.2.0                   :  1.2.1 (OK)
qdarkstyle >=3.0.2;<3.1.0             :  3.0.3 (OK)
qstylizer >=0.1.10                    :  0.2.2 (OK)
qtawesome >=1.0.2                     :  1.1.1 (OK)
qtconsole >=5.3.2;<5.4.0              :  5.3.2 (OK)
qtpy >=2.1.0                          :  2.2.1 (OK)
rtree >=0.9.7                         :  1.0.0 (OK)
setuptools >=49.6.0                   :  65.4.1 (OK)
sphinx >=0.6.6                        :  4.5.0 (OK)
spyder_kernels >=2.3.3;<2.4.0         :  2.3.3 (OK)
textdistance >=4.2.0                  :  4.5.0 (OK)
three_merge >=0.1.1                   :  0.1.1 (OK)
watchdog >=0.10.3                     :  2.1.9 (OK)
xdg >=0.26                            :  0.28 (OK)
zmq >=22.1.0                          :  24.0.1 (OK)

\# Optional:
cython >=0.21                         :  0.29.32 (OK)
matplotlib >=3.0.0                    :  3.6.0 (OK)
numpy >=1.7                           :  1.23.3 (OK)
pandas >=1.1.1                        :  1.5.0 (OK)
scipy >=0.17.0                        :  1.9.1 (OK)
sympy >=0.7.3                         :  1.11.1 (OK)

\# Spyder plugins:
spyder_notebook.notebookplugin 0.4.0  :  0.4.0 (OK)
spyder_okvim.spyder.plugin 0.0.1.dev0 :  0.0.1-dev0 (OK)

**Comment by ccordoba12** [comment]
Hey @schmoelder, thanks for reporting. A couple of comments:

* Please uninstall this plugin `spyder_okvim.spyder.plugin` and try again. Perhaps there's a conflict between the two.
* Please go to this entry in the File menu

    ![imagen](https://user-images.githubusercontent.com/365293/138761482-598fa96c-13f8-4dde-ae9a-e18ac20a7c69.png)

    and select `Verbose`:

    ![imagen](https://user-images.githubusercontent.com/365293/138761597-e833892d-888c-4e93-99fd-6acf98dde1cc.png)

    After Spyder restarts, go to the `Tools > Debug logs` menu

    ![imagen](https://user-images.githubusercontent.com/365293/138761756-2af03a24-21c6-47bb-8354-1f2ec87a1e83.png)

    open `spyder-debug.log` and upload it here.

**Comment by schmoelder** [comment]
Hey @ccordoba12,
thanks so much for investigating this.

> Please uninstall this plugin spyder_okvim.spyder.plugin and try again. Perhaps there's a conflict between the two.

I did, unfortunately, that didn't help.

> open spyder-debug.log and upload it here.

Here you go: https://gist.github.com/schmoelder/bcfa4366fd68493573cee9eb9826c80e

If there is anything else I can do, please let me know! :)

**Comment by jitseniesen** [comment]
I don't see anything wrong in the logs. The notebook server is started as it should. Here are some more things you can try:
1. Go to the options menu of the Notebook pane (this is the button with three horizontal lines in the upper right corner) and click on "Server info". Look for error messages. The message "No QCoreApplication instance found" at the top of the log is harmless.
2. According to the debug log, the notebook server is started with the command
   ```
   /home/jo/software/miniconda3/envs/chromapy/lib/python3.9/site-packages/spyder_notebook/server/main.py --no-browser --notebook-dir=/tmp/spyder-jo/notebooks --NotebookApp.password= KernelSpecManager.kernel_spec_class=spyder.plugins.ipythonconsole.utils.kernelspec.SpyderKernelSpec --dark
   ```
   Run this command from the command line inside the chromapy environment and look for errors. One of the messages should give you a URL; open that in a web browser and make sure that it works.
3. Install Spyder and the spyder-notebook plugin in a fresh environment.

**Comment by dererumenergetica** [comment]
Hi, just did a clean installation of
- Anaconda-Navigator 2.3.2
- launched and updated Spyder 5.3.3
- in terminal: conda install spyder-notebook -c conda-forge
- open Ananconda-Navigator - Environments and search for "Spyder" 
- update all dependencies of spyder-notebook and ensure it's marked running
- restart Spyder 
should work now.

**Comment by schmoelder** [comment]
> Install Spyder and the spyder-notebook plugin in a fresh environment.

I created a clean (`spyder`) environment, the issue still persists.

>Go to the options menu of the Notebook pane (this is the button with three horizontal lines in the upper right corner) and click on "Server info". Look for error messages. The message "No QCoreApplication instance found" at the top of the log is harmless.

No Errors here. This is the entire output:
```
No QCoreApplication instance found. Application patches not applied. You have to call load_stylesheet function after instantiation of QApplication to take effect. 
[I 11:09:08.739 SpyderNotebookServer] Serving notebooks from local directory: /tmp/spyder-jo/notebooks
[I 11:09:08.740 SpyderNotebookServer] Jupyter Notebook 6.5.1 is running at:
[I 11:09:08.740 SpyderNotebookServer] http://localhost:8888/?token=223038de960f79d715d0be98a2716256265b583793348a11
[I 11:09:08.740 SpyderNotebookServer]  or http://127.0.0.1:8888/?token=223038de960f79d715d0be98a2716256265b583793348a11
[I 11:09:08.740 SpyderNotebookServer] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 11:09:08.743 SpyderNotebookServer] 
    
    To access the notebook, open this file in a browser:
        file:///home/jo/.local/share/jupyter/runtime/nbserver-859616-open.html
    Or copy and paste one of these URLs:
        http://localhost:8888/?token=223038de960f79d715d0be98a2716256265b583793348a11
     or http://127.0.0.1:8888/?token=223038de960f79d715d0be98a2716256265b583793348a11
```

> 2\. According to the debug log, the notebook server is started with the command
>         ```
>         /home/jo/software/miniconda3/envs/chromapy/lib/python3.9/site-packages/spyder_notebook/server/main.py --no-browser --notebook-dir=/tmp/spyder-jo/notebooks --NotebookApp.password= KernelSpecManager.kernel_spec_class=spyder.plugins.ipythonconsole.utils.kernelspec.SpyderKernelSpec --dark
>         ```
>         Run this command from the command line inside the chromapy environment and look for errors. One of the messages should give you a URL; open that in a web browser and make sure that it works.

I did that (in my new clean spyder environment) and it crashes. This ist the output:

```
(spyder) jo@matebook:~$ /home/jo/software/miniconda3/envs/spyder/lib/python3.9/site-packages/spyder_notebook/server/main.py --no-browser --notebook-dir=/tmp/spyder-jo/notebooks --NotebookApp.password= KernelSpecManager.kernel_spec_class=spyder.plugins.ipythonconsole.utils.kernelspec.SpyderKernelSpec --dark
/home/jo/software/miniconda3/envs/spyder/lib/python3.9/site-packages/spyder_notebook/server/main.py: Zeile 4: Entry point for server rendering notebooks for Spyder.: Befehl nicht gefunden
import-im6.q16: attempt to perform an operation not allowed by the security policy `PS' @ error/constitute.c/IsCoderAuthorized/421.
/home/jo/software/miniconda3/envs/spyder/lib/python3.9/site-packages/spyder_notebook/server/main.py: Zeile 7: from: Befehl nicht gefunden
/home/jo/software/miniconda3/envs/spyder/lib/python3.9/site-packages/spyder_notebook/server/main.py: Zeile 8: from: Befehl nicht gefunden
/home/jo/software/miniconda3/envs/spyder/lib/python3.9/site-packages/spyder_notebook/server/main.py: Zeile 9: from: Befehl nicht gefunden
/home/jo/software/miniconda3/envs/spyder/lib/python3.9/site-packages/spyder_notebook/server/main.py: Zeile 10: from: Befehl nicht gefunden
/home/jo/software/miniconda3/envs/spyder/lib/python3.9/site-packages/spyder_notebook/server/main.py: Zeile 11: from: Befehl nicht gefunden
/home/jo/software/miniconda3/envs/spyder/lib/python3.9/site-packages/spyder_notebook/server/main.py: Zeile 13: Syntaxfehler beim unerwarteten Wort »(«
/home/jo/software/miniconda3/envs/spyder/lib/python3.9/site-packages/spyder_notebook/server/main.py: Zeile 13: `HERE = os.path.dirname(__file__)'
```

Unfortunately, it's in German. I could try to change the system language if that helps.

**Comment by StevenChicken** [comment]
Not working for me either unfortunately :( Thanks for your efforts guys though!

**Comment by equaeghe** [comment]
I have seemingly the same issue. Namely, I get the notebook tab, but no notebook interface is visible there:
![Screenshot_20221206_140420](https://user-images.githubusercontent.com/601177/205920953-10a8c4b8-01a6-44a5-94c0-33c842278d47.png)
From the verbose logs, I found the command that is (supposed to be?) run:
```
python /usr/lib/python3.10/site-packages/spyder_notebook/server/main.py --no-browser --notebook-dir=/tmp/spyder-equaeghe/notebooks --NotebookApp.password= --KernelSpecManager.kernel_spec_class=spyder.plugins.ipythonconsole.utils.kernelspec.SpyderKernelSpec
```
(I first did it without the `python` in front, but the file is not executable.) Running this file results in
```
No QCoreApplication instance found. Application patches not applied. You have to call load_stylesheet function after instantiation of QApplication to take effect. 
[I 14:10:12.020 SpyderNotebookServer] Loading IPython parallel extension
[I 14:10:12.024 SpyderNotebookServer] De port 8888 is al in gebruik, proberen een andere port.
[I 14:10:12.025 SpyderNotebookServer] De port 8889 is al in gebruik, proberen een andere port.
[I 14:10:12.026 SpyderNotebookServer] Notebooks uit lokale map activeren: /tmp/spyder-equaeghe/notebooks
[I 14:10:12.026 SpyderNotebookServer] Jupyter Notebook 6.4.12 is running at:
[I 14:10:12.026 SpyderNotebookServer] http://localhost:8890/?token=14a22703c2edb3d9fd78b3c943292c07333e1027775ededb
[I 14:10:12.026 SpyderNotebookServer]  or http://127.0.0.1:8890/?token=14a22703c2edb3d9fd78b3c943292c07333e1027775ededb
[I 14:10:12.026 SpyderNotebookServer] Gebruik Control-C om deze server te stoppen en sluit alle kernels af (twee keer om bevestiging over te slaan).
[C 14:10:12.031 SpyderNotebookServer] 
    
    To access the notebook, open this file in a browser:
        file:///home/equaeghe/.local/share/jupyter/runtime/nbserver-54769-open.html
    Or copy and paste one of these URLs:
        http://localhost:8890/?token=14a22703c2edb3d9fd78b3c943292c07333e1027775ededb
     or http://127.0.0.1:8890/?token=14a22703c2edb3d9fd78b3c943292c07333e1027775ededb

```
and the specified URL redirects to another page, we see a strange view, but there is something there:
![Screenshot_20221206_141232](https://user-images.githubusercontent.com/601177/205921844-07adf466-28f5-4272-995b-b3592fc0f15d.png)

What steps can I take to try and fix this issue?

**Comment by ccordoba12** [comment]
@equaeghe, I think this problem could be due to permission errors caused because you installed Spyder and Spyder-notebook system-wide.

So, please create an isolated virtualenv in your home directory and install Spyder-notebook there. Perhaps that fixes the issue for you.

**Comment by d9d6ka** [comment]
> @equaeghe, I think this problem could be due to permission errors caused because you installed Spyder and Spyder-notebook system-wide.
> 
> So, please create an isolated virtualenv in your home directory and install Spyder-notebook there. Perhaps that fixes the issue for you.

I've tried to do this on Windows 11, and still no effect. I keep receiving a timeout error.

**Comment by schmoelder** [comment]
I also still have this issue, now on spyder 5.4.2

I do get some new output in the console, however. Don't know if it's related but maybe it helps:
```
/home/jo/software/miniconda3/envs/dev/lib/python3.10/site-packages/jupyter_client/threaded.py:73: RuntimeWarning: ZMQStream only supports the base zmq.Socket class.

                Use zmq.Socket(shadow=other_socket)
                or `ctx.socket(zmq.DEALER, socket_class=zmq.Socket)`
                to create a base zmq.Socket object,
                no matter what other kind of socket your Context creates.

  self.stream = zmqstream.ZMQStream(self.socket, self.ioloop)
```

**Comment by ccordoba12** [comment]
@schmoelder, that warning is unrelated to this problem. On Linux it could be related to issue https://github.com/spyder-ide/spyder/issues/20358.

So, I'd like to ask you: is the Help pane working for you as expected?

**Comment by 64kbyte** [comment]
I ran into the same two related issues:
1. Notebook showing up blank
2. Help pane showing up blank

I started with a Miniconda 4.10 environment. Followed directions to install spyder like this:
`conda create -c conda-forge -n spyder-env spyder numpy scipy pandas matplotlib sympy cython opencv spyder-notebook`

The above appears to require an update of python to 4.11. I think this is what's causing the issues.

I setup the environment again. This time, without pointing to conda-forge:
`conda create -n spyder-env spyder numpy scipy pandas matplotlib sympy cython opencv`

Looks like python 4.10.9 remains. And spyder is the older version 5.3.3. And help pane works.

Then installed the notebook plugin from conda-forge:
`conda install spyder-notebook -c conda-forge`

Appears to work!

Now if I could only figure out how to get the debugger working in notebook... (maybe it's not supported yet)?

**Comment by d9d6ka** [comment]
> So, I'd like to ask you: is the Help pane working for you as expected?

Well, sort of. Maybe I don't fully understand HOW it should work. When I press <kbd>CTRL</kbd> + <kbd>I</kbd> in front of the object the help topic appears in the Help pane. But the Object search line doesn't work, it ignores any input I provide.

It takes place either with and without spyder-notebook and its depndecies installed.

**Comment by d9d6ka** [comment]
UPD: tried on MacOS Monterrey in fresly created venv (Python 3.10.6).

I've installed spyder and spyder-notebook via pip. Everything works as expected, both notepad and help pane.

**Comment by ccordoba12** [comment]
@64kbyte, you said:

> Now if I could only figure out how to get the debugger working in notebook... (maybe it's not supported yet)?

That use case is still not supported but we'll try to in the future.

Also, what's your operating system?

**Comment by ccordoba12** [comment]
@d9d6ka, you said

> In Windows 11 under venv help and notebook don't work. If installed system-wide help pane and notebooks work as expected.

That's very strange. What's your Python version?

Also, @dalthviz, could you check if Spyder-notebook is working for you if installed in a conda env on Windows?

**Comment by d9d6ka** [comment]
> @d9d6ka, you said
> 
> > In Windows 11 under venv help and notebook don't work. If installed system-wide help pane and notebooks work as expected.
> 
> That's very strange. What's your Python version?

Well, I don't know, what happened, but help pane started working...

On my Windows machine Python 3.11.0 is installed. System-wide everything works. In venv notebook throws a timeout error.

I'll use a system-wide installed Spyder for now. Anyway thanks for this add-on, hope the source of the problem will be found.

**Comment by 64kbyte** [comment]
> Also, what's your operating system?

I'm on Ubuntu 22.04.

I dug a little deeper and played around with conda package versions. Looks the culprit may be in the interactions with the **fontconfig** package. A default install from the conda-forge channel will bring in fontconfig=2.14.2. I decided to try one version prior.

I made a fresh environment with:

`conda create -c conda-forge -n pydev fontconfig=2.14.1 spyder spyder-notebook numpy scipy pandas matplotlib sympy cython opencv`

Both help and notebook show up and are functional with Python 3.11 and spyder 5.4.2 and spyder-notebook 0.4.0.

**Comment by schmoelder** [comment]
Sorry, was afk yesterday...

> So, I'd like to ask you: is the Help pane working for you as expected?

You're right, it's actually not working. Since I don't use it much, I had not noticed that.

> Both help and notebook show up and are functional with Python 3.11 and spyder 5.4.2 and spyder-notebook 0.4.0.

I'm still on Python 3.10 but using spyder 5.4.2 and spyder-notebook 0.4.0 with fontconfig=2.14.1 (and 2.14.2 for that matter) did not solve the issue for me.

**Comment by dalthviz** [comment]
> Also, @dalthviz, could you check if Spyder-notebook is working for you if installed in a conda env on Windows?

Tried creating a conda env (`conda create -n spyder-notebook -c conda-forge python=3.10 spyder spyder-notebook`) but seems like is working for me. The env spec:

<details>

```
# Name                    Version                   Build  Channel
alabaster                 0.7.13             pyhd8ed1ab_0    conda-forge
anyio                     3.6.2              pyhd8ed1ab_0    conda-forge
argon2-cffi               21.3.0             pyhd8ed1ab_0    conda-forge
argon2-cffi-bindings      21.2.0          py310h8d17308_3    conda-forge
arrow                     1.2.3              pyhd8ed1ab_0    conda-forge
astroid                   2.13.3          py310h5588dad_0    conda-forge
asttokens                 2.2.1              pyhd8ed1ab_0    conda-forge
atomicwrites              1.4.1              pyhd8ed1ab_0    conda-forge
attrs                     22.2.0             pyh71513ae_0    conda-forge
autopep8                  1.6.0              pyhd8ed1ab_1    conda-forge
babel                     2.11.0             pyhd8ed1ab_0    conda-forge
backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
backports                 1.0                pyhd8ed1ab_3    conda-forge
backports.functools_lru_cache 1.6.4              pyhd8ed1ab_0    conda-forge
bcrypt                    3.2.2           py310h8d17308_1    conda-forge
beautifulsoup4            4.11.1             pyha770c72_0    conda-forge
binaryornot               0.4.4                      py_1    conda-forge
black                     22.12.0         py310h5588dad_0    conda-forge
bleach                    6.0.0              pyhd8ed1ab_0    conda-forge
brotlipy                  0.7.0           py310h8d17308_1005    conda-forge
bzip2                     1.0.8                h8ffe710_4    conda-forge
ca-certificates           2022.12.7            h5b45459_0    conda-forge
certifi                   2022.12.7          pyhd8ed1ab_0    conda-forge
cffi                      1.15.1          py310h628cb3f_3    conda-forge
chardet                   5.1.0           py310h5588dad_0    conda-forge
charset-normalizer        2.1.1              pyhd8ed1ab_0    conda-forge
click                     8.1.3           win_pyhd8ed1ab_2    conda-forge
cloudpickle               2.2.1              pyhd8ed1ab_0    conda-forge
colorama                  0.4.6              pyhd8ed1ab_0    conda-forge
comm                      0.1.2              pyhd8ed1ab_0    conda-forge
cookiecutter              2.1.1              pyh6c4a22f_0    conda-forge
cryptography              39.0.0          py310h6e82f81_0    conda-forge
debugpy                   1.6.6           py310h00ffb61_0    conda-forge
decorator                 5.1.1              pyhd8ed1ab_0    conda-forge
defusedxml                0.7.1              pyhd8ed1ab_0    conda-forge
diff-match-patch          20200713           pyh9f0ad1d_0    conda-forge
dill                      0.3.6              pyhd8ed1ab_1    conda-forge
docstring-to-markdown     0.11               pyhd8ed1ab_0    conda-forge
docutils                  0.19            py310h5588dad_1    conda-forge
entrypoints               0.4                pyhd8ed1ab_0    conda-forge
executing                 1.2.0              pyhd8ed1ab_0    conda-forge
flake8                    6.0.0              pyhd8ed1ab_0    conda-forge
flit-core                 3.8.0              pyhd8ed1ab_0    conda-forge
gettext                   0.21.1               h5728263_0    conda-forge
glib                      2.74.1               h12be248_1    conda-forge
glib-tools                2.74.1               h12be248_1    conda-forge
gst-plugins-base          1.21.3               h001b923_1    conda-forge
gstreamer                 1.21.3               h6b5321d_1    conda-forge
icu                       70.1                 h0e60522_0    conda-forge
idna                      3.4                pyhd8ed1ab_0    conda-forge
imagesize                 1.4.1              pyhd8ed1ab_0    conda-forge
importlib-metadata        6.0.0              pyha770c72_0    conda-forge
importlib_metadata        6.0.0                hd8ed1ab_0    conda-forge
importlib_resources       5.10.2             pyhd8ed1ab_0    conda-forge
inflection                0.5.1              pyh9f0ad1d_0    conda-forge
intervaltree              3.0.2                      py_0    conda-forge
ipykernel                 6.20.2             pyh025b116_0    conda-forge
ipython                   8.9.0              pyh08f2357_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
isort                     5.12.0             pyhd8ed1ab_1    conda-forge
jaraco.classes            3.2.3              pyhd8ed1ab_0    conda-forge
jedi                      0.18.2             pyhd8ed1ab_0    conda-forge
jellyfish                 0.9.0           py310h8d17308_2    conda-forge
jinja2                    3.1.2              pyhd8ed1ab_1    conda-forge
jinja2-time               0.2.0              pyhd8ed1ab_3    conda-forge
jpeg                      9e                   h8ffe710_2    conda-forge
jsonschema                4.17.3             pyhd8ed1ab_0    conda-forge
jupyter_client            7.4.9              pyhd8ed1ab_0    conda-forge
jupyter_core              5.1.5           py310h5588dad_0    conda-forge
jupyter_events            0.6.3              pyhd8ed1ab_0    conda-forge
jupyter_server            2.1.0              pyhd8ed1ab_0    conda-forge
jupyter_server_terminals  0.4.4              pyhd8ed1ab_1    conda-forge
jupyterlab_pygments       0.2.2              pyhd8ed1ab_0    conda-forge
keyring                   23.13.1         py310h5588dad_0    conda-forge
krb5                      1.20.1               heb0366b_0    conda-forge
lazy-object-proxy         1.9.0           py310h8d17308_0    conda-forge
libclang                  15.0.7          default_h77d9078_0    conda-forge
libclang13                15.0.7          default_h77d9078_0    conda-forge
libffi                    3.4.2                h8ffe710_5    conda-forge
libglib                   2.74.1               he8f3873_1    conda-forge
libiconv                  1.17                 h8ffe710_0    conda-forge
libogg                    1.3.4                h8ffe710_1    conda-forge
libpng                    1.6.39               h19919ed_0    conda-forge
libsodium                 1.0.18               h8d14728_1    conda-forge
libspatialindex           1.9.3                h39d44d4_4    conda-forge
libsqlite                 3.40.0               hcfcfb64_0    conda-forge
libvorbis                 1.3.7                h0e60522_0    conda-forge
libwebp                   1.2.4                hcfcfb64_1    conda-forge
libwebp-base              1.2.4                h8ffe710_0    conda-forge
libzlib                   1.2.13               hcfcfb64_4    conda-forge
markupsafe                2.1.2           py310h8d17308_0    conda-forge
matplotlib-inline         0.1.6              pyhd8ed1ab_0    conda-forge
mccabe                    0.7.0              pyhd8ed1ab_0    conda-forge
mistune                   2.0.4              pyhd8ed1ab_0    conda-forge
more-itertools            9.0.0              pyhd8ed1ab_0    conda-forge
mypy_extensions           0.4.3           py310h5588dad_6    conda-forge
nbclassic                 0.4.8              pyhd8ed1ab_0    conda-forge
nbclient                  0.7.2              pyhd8ed1ab_0    conda-forge
nbconvert                 7.2.9              pyhd8ed1ab_0    conda-forge
nbconvert-core            7.2.9              pyhd8ed1ab_0    conda-forge
nbconvert-pandoc          7.2.9              pyhd8ed1ab_0    conda-forge
nbformat                  5.7.3              pyhd8ed1ab_0    conda-forge
nest-asyncio              1.5.6              pyhd8ed1ab_0    conda-forge
notebook                  6.5.2              pyha770c72_1    conda-forge
notebook-shim             0.2.2              pyhd8ed1ab_0    conda-forge
numpydoc                  1.5.0              pyhd8ed1ab_0    conda-forge
openssl                   3.0.7                hcfcfb64_2    conda-forge
packaging                 23.0               pyhd8ed1ab_0    conda-forge
pandoc                    2.19.2               h57928b3_1    conda-forge
pandocfilters             1.5.0              pyhd8ed1ab_0    conda-forge
paramiko                  3.0.0              pyhd8ed1ab_0    conda-forge
parso                     0.8.3              pyhd8ed1ab_0    conda-forge
pathspec                  0.11.0             pyhd8ed1ab_0    conda-forge
pcre2                     10.40                h17e33f8_0    conda-forge
pexpect                   4.8.0              pyh1a96a4e_2    conda-forge
pickleshare               0.7.5                   py_1003    conda-forge
pip                       22.3.1             pyhd8ed1ab_0    conda-forge
pkgutil-resolve-name      1.3.10             pyhd8ed1ab_0    conda-forge
platformdirs              2.6.2              pyhd8ed1ab_0    conda-forge
pluggy                    1.0.0              pyhd8ed1ab_5    conda-forge
ply                       3.11                       py_1    conda-forge
prometheus_client         0.16.0             pyhd8ed1ab_0    conda-forge
prompt-toolkit            3.0.36             pyha770c72_0    conda-forge
psutil                    5.9.4           py310h8d17308_0    conda-forge
ptyprocess                0.7.0              pyhd3deb0d_0    conda-forge
pure_eval                 0.2.2              pyhd8ed1ab_0    conda-forge
pycodestyle               2.10.0             pyhd8ed1ab_0    conda-forge
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pydocstyle                6.2.3              pyhd8ed1ab_0    conda-forge
pyflakes                  3.0.1              pyhd8ed1ab_0    conda-forge
pygments                  2.14.0             pyhd8ed1ab_0    conda-forge
pylint                    2.15.10            pyhd8ed1ab_0    conda-forge
pylint-venv               2.3.0              pyhd8ed1ab_0    conda-forge
pyls-spyder               0.4.0              pyhd8ed1ab_0    conda-forge
pynacl                    1.5.0           py310h635b8f1_2    conda-forge
pyopenssl                 23.0.0             pyhd8ed1ab_0    conda-forge
pyqt                      5.15.7          py310h1fd54f2_3    conda-forge
pyqt5-sip                 12.11.0         py310h00ffb61_3    conda-forge
pyqtwebengine             5.15.7          py310he49db7d_3    conda-forge
pyrsistent                0.19.3          py310h8d17308_0    conda-forge
pysocks                   1.7.1              pyh0701188_6    conda-forge
python                    3.10.8          h4de0772_0_cpython    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python-fastjsonschema     2.16.2             pyhd8ed1ab_0    conda-forge
python-json-logger        2.0.4              pyhd8ed1ab_0    conda-forge
python-lsp-black          1.2.1              pyhd8ed1ab_0    conda-forge
python-lsp-jsonrpc        1.0.0              pyhd8ed1ab_0    conda-forge
python-lsp-server         1.7.1                hd8ed1ab_0    conda-forge
python-lsp-server-base    1.7.1              pyhd8ed1ab_0    conda-forge
python-slugify            8.0.0              pyhd8ed1ab_0    conda-forge
python_abi                3.10                    3_cp310    conda-forge
pytoolconfig              1.2.4              pyhd8ed1ab_1    conda-forge
pytz                      2022.7.1           pyhd8ed1ab_0    conda-forge
pywin32                   304             py310h00ffb61_2    conda-forge
pywin32-ctypes            0.2.0           py310h5588dad_1006    conda-forge
pywinpty                  2.0.10          py310h00ffb61_0    conda-forge
pyyaml                    6.0             py310h8d17308_5    conda-forge
pyzmq                     25.0.0          py310hcd737a0_0    conda-forge
qdarkstyle                3.0.3              pyhd8ed1ab_0    conda-forge
qstylizer                 0.2.2              pyhd8ed1ab_0    conda-forge
qt-main                   5.15.6               h9580fe5_6    conda-forge
qt-webengine              5.15.4               h0bdee70_3    conda-forge
qtawesome                 1.2.2              pyhd8ed1ab_0    conda-forge
qtconsole                 5.4.0              pyhd8ed1ab_0    conda-forge
qtconsole-base            5.4.0              pyha770c72_0    conda-forge
qtpy                      2.3.0              pyhd8ed1ab_0    conda-forge
requests                  2.28.2             pyhd8ed1ab_0    conda-forge
rfc3339-validator         0.1.4              pyhd8ed1ab_0    conda-forge
rfc3986-validator         0.1.1              pyh9f0ad1d_0    conda-forge
rope                      1.7.0              pyhd8ed1ab_0    conda-forge
rtree                     1.0.1           py310h1cbd46b_1    conda-forge
send2trash                1.8.0              pyhd8ed1ab_0    conda-forge
setuptools                66.1.1             pyhd8ed1ab_0    conda-forge
sip                       6.7.6           py310h00ffb61_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
sniffio                   1.3.0              pyhd8ed1ab_0    conda-forge
snowballstemmer           2.2.0              pyhd8ed1ab_0    conda-forge
sortedcontainers          2.4.0              pyhd8ed1ab_0    conda-forge
soupsieve                 2.3.2.post1        pyhd8ed1ab_0    conda-forge
sphinx                    6.1.3              pyhd8ed1ab_0    conda-forge
sphinxcontrib-applehelp   1.0.4              pyhd8ed1ab_0    conda-forge
sphinxcontrib-devhelp     1.0.2                      py_0    conda-forge
sphinxcontrib-htmlhelp    2.0.0              pyhd8ed1ab_0    conda-forge
sphinxcontrib-jsmath      1.0.1                      py_0    conda-forge
sphinxcontrib-qthelp      1.0.3                      py_0    conda-forge
sphinxcontrib-serializinghtml 1.1.5              pyhd8ed1ab_2    conda-forge
spyder                    5.4.2           py310h5588dad_0    conda-forge
spyder-kernels            2.4.2           win_pyhd8ed1ab_0    conda-forge
spyder-notebook           0.4.0              pyh1a96a4e_0    conda-forge
stack_data                0.6.2              pyhd8ed1ab_0    conda-forge
terminado                 0.15.0          py310h5588dad_0    conda-forge
text-unidecode            1.3                        py_0    conda-forge
textdistance              4.5.0              pyhd8ed1ab_0    conda-forge
three-merge               0.1.1              pyh9f0ad1d_0    conda-forge
tinycss2                  1.2.1              pyhd8ed1ab_0    conda-forge
tk                        8.6.12               h8ffe710_0    conda-forge
toml                      0.10.2             pyhd8ed1ab_0    conda-forge
tomli                     2.0.1              pyhd8ed1ab_0    conda-forge
tomlkit                   0.11.6             pyha770c72_0    conda-forge
tornado                   6.2             py310h8d17308_1    conda-forge
traitlets                 5.8.1              pyhd8ed1ab_0    conda-forge
typing                    3.10.0.0           pyhd8ed1ab_0    conda-forge
typing-extensions         4.4.0                hd8ed1ab_0    conda-forge
typing_extensions         4.4.0              pyha770c72_0    conda-forge
tzdata                    2022g                h191b570_0    conda-forge
ucrt                      10.0.22621.0         h57928b3_0    conda-forge
ujson                     5.5.0           py310h00ffb61_1    conda-forge
unidecode                 1.3.6              pyhd8ed1ab_0    conda-forge
urllib3                   1.26.14            pyhd8ed1ab_0    conda-forge
vc                        14.3                hb6edc58_10    conda-forge
vs2015_runtime            14.34.31931         h4c5c07a_10    conda-forge
watchdog                  2.2.1           py310h5588dad_0    conda-forge
wcwidth                   0.2.6              pyhd8ed1ab_0    conda-forge
webencodings              0.5.1                      py_1    conda-forge
websocket-client          1.5.0              pyhd8ed1ab_0    conda-forge
whatthepatch              1.0.3              pyhd8ed1ab_0    conda-forge
wheel                     0.38.4             pyhd8ed1ab_0    conda-forge
win_inet_pton             1.1.0              pyhd8ed1ab_6    conda-forge
winpty                    0.4.3                         4    conda-forge
wrapt                     1.14.1          py310h8d17308_1    conda-forge
xz                        5.2.6                h8d14728_0    conda-forge
yaml                      0.2.5                h8ffe710_2    conda-forge
yapf                      0.32.0             pyhd8ed1ab_0    conda-forge
zeromq                    4.3.4                h0e60522_1    conda-forge
zipp                      3.12.0             pyhd8ed1ab_0    conda-forge
zstd                      1.5.2                h12be248_6    conda-forge
```

</details>

Also, seems like the Help pane is not working too, right? Maybe then the issue cpuld be related with QWebEngine process not being able to launch from that specific non system-wide venv? Also, where is located the venv where things are not working? If it is located in a network drive maybe the issue could be related to https://bugreports.qt.io/browse/QTBUG-84632

**Comment by ccordoba12** [comment]
Hey guys, I think this will be solved when we release Spyder 5.4.3 next month thanks to the fix in https://github.com/spyder-ide/spyder/pull/20482. That should solve the problems @schmoelder is having on Linux and @d9d6ka on Windows.

We'll let you know when that release is out so you can try Spyder-notebook again afterwards.

**Comment by jitseniesen** [comment]
Fixed by #410
